// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _19012017time1049 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19012017time1049));
        
        string IMigrationMetadata.Id
        {
            get { return "201701190749519_19-01-2017-time-10-49"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
